// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe2ry3gBMcN6eSxIVVGaaFhizUq1owaBc',
    appId: '1:924312376333:web:3e82aa156ba9718e487144',
    messagingSenderId: '924312376333',
    projectId: 'millo-df2f3',
    authDomain: 'millo-df2f3.firebaseapp.com',
    storageBucket: 'millo-df2f3.appspot.com',
    measurementId: 'G-9VL4753R3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARb5KgNQNXFpM2vRJaXdcq4nDL68dLB9g',
    appId: '1:924312376333:android:57e465eeecb53aee487144',
    messagingSenderId: '924312376333',
    projectId: 'millo-df2f3',
    storageBucket: 'millo-df2f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz_ajYI34SO6jZpzv2CY-FMriZXSvy18I',
    appId: '1:924312376333:ios:bf76c4c1f136288b487144',
    messagingSenderId: '924312376333',
    projectId: 'millo-df2f3',
    storageBucket: 'millo-df2f3.appspot.com',
    iosClientId: '924312376333-9oc4h1h6njd29l299k5h8s6o0ebci77j.apps.googleusercontent.com',
    iosBundleId: 'com.vendedor.app.vendedor',
  );
}
